spring.application.name=sms

spring.datasource.url=jdbc:mysql://localhost:3306/sms
spring.datasource.username=root
spring.datasource.password=Lovemysql@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
security.jwt.secret-key=MWYyZDFlMmU2N2RmNGQxNmMzZjM3YjViOTQwZDVjMjliMWQ0MzA3NWFjYTVlOWJjYjg2Y2U1NTVmZWRjYTI3NQ==
security.jwt.expiration-ms=86400000
